// ===== MATHCRAFT QUESTION BANK =====
// Adapted from public math datasets — MCQ format

const QUESTIONS = {
  trigonometry: [
    { id:"t1", question:"What is sin(90°)?", options:["0","1","√2/2","undefined"], answer:1, difficulty:"easy", xp:20, explanation:"sin(90°) = 1. At 90°, the opposite side equals the hypotenuse in a unit circle.", tip:"Remember SOHCAHTOA — sin = Opposite / Hypotenuse." },
    { id:"t2", question:"What is cos(0°)?", options:["0","1","-1","∞"], answer:1, difficulty:"easy", xp:20, explanation:"cos(0°) = 1. At 0°, the adjacent equals the hypotenuse.", tip:"cos starts at 1 and decreases as angle increases to 90°." },
    { id:"t3", question:"What is tan(45°)?", options:["0","√3","1","undefined"], answer:2, difficulty:"easy", xp:20, explanation:"tan(45°) = sin(45°)/cos(45°) = (√2/2)/(√2/2) = 1.", tip:"tan(45°) = 1 is a key value to memorize." },
    { id:"t4", question:"If sin(θ) = 3/5, what is cos(θ)?", options:["4/5","3/4","5/3","1/5"], answer:0, difficulty:"medium", xp:40, explanation:"Using sin²θ + cos²θ = 1: (3/5)² + cos²θ = 1 → cos²θ = 16/25 → cos θ = 4/5.", tip:"Always use the Pythagorean identity: sin²θ + cos²θ = 1." },
    { id:"t5", question:"What is the value of sin(30°)?", options:["√3/2","1/2","1","0"], answer:1, difficulty:"easy", xp:20, explanation:"sin(30°) = 1/2. This is a standard trigonometric value.", tip:"Key angles: sin(30)=1/2, sin(45)=√2/2, sin(60)=√3/2." },
    { id:"t6", question:"tan(θ) = sin(θ)/cos(θ). If sin(θ) = 0.6 and cos(θ) = 0.8, what is tan(θ)?", options:["0.75","1.33","0.48","1.5"], answer:0, difficulty:"medium", xp:40, explanation:"tan(θ) = 0.6/0.8 = 0.75.", tip:"tan = sin ÷ cos. Simple division once you have both values." },
    { id:"t7", question:"What is sin²θ + cos²θ equal to?", options:["0","2","1","sin(2θ)"], answer:2, difficulty:"easy", xp:20, explanation:"sin²θ + cos²θ = 1 is the fundamental Pythagorean identity.", tip:"This identity is used in almost every trig problem — memorize it!" },
    { id:"t8", question:"What is cos(90°)?", options:["1","0","-1","√3/2"], answer:1, difficulty:"easy", xp:20, explanation:"cos(90°) = 0. At 90°, the adjacent side is 0.", tip:"On the unit circle, cos gives the x-coordinate. At 90°, x = 0." },
    { id:"t9", question:"Which of the following is equal to 1 + tan²θ?", options:["sec²θ","cosec²θ","cos²θ","cot²θ"], answer:0, difficulty:"medium", xp:40, explanation:"1 + tan²θ = sec²θ is derived from dividing sin²θ + cos²θ = 1 by cos²θ.", tip:"Three Pythagorean identities: sin²+cos²=1, 1+tan²=sec², 1+cot²=cosec²." },
    { id:"t10", question:"sin(60°) = ?", options:["1/2","√3/2","√2/2","1"], answer:1, difficulty:"easy", xp:20, explanation:"sin(60°) = √3/2 ≈ 0.866.", tip:"sin(60) = cos(30) = √3/2. Pairs of complementary angles share values." },
    { id:"t11", question:"What is the period of sin(x)?", options:["π","2π","π/2","4π"], answer:1, difficulty:"medium", xp:40, explanation:"The period of sin(x) is 2π — it completes one full cycle every 2π radians.", tip:"Period = 2π/|b| for sin(bx). For sin(x), b=1 so period = 2π." },
    { id:"t12", question:"If tan(θ) = 1, what is θ (in degrees)?", options:["30°","60°","45°","90°"], answer:2, difficulty:"easy", xp:20, explanation:"tan(45°) = 1. This is a standard result.", tip:"tan(45) = 1 because sin(45) = cos(45) = √2/2." },
    { id:"t13", question:"What is the value of sin(0°)?", options:["1","0","∞","-1"], answer:1, difficulty:"easy", xp:20, explanation:"sin(0°) = 0. At 0°, the opposite side is 0.", tip:"sin starts at 0, peaks at 1 (90°), then goes back through 0 at 180°." },
    { id:"t14", question:"cot(θ) = ?", options:["sin/cos","cos/sin","1/sin","1/cos"], answer:1, difficulty:"medium", xp:40, explanation:"cot(θ) = cos(θ)/sin(θ) = 1/tan(θ).", tip:"cot is the reciprocal of tan. Think: co-tangent flips the tangent ratio." },
    { id:"t15", question:"In a right triangle with hypotenuse 10 and opposite side 6, what is sin(θ)?", options:["0.6","0.8","0.75","1.2"], answer:0, difficulty:"medium", xp:40, explanation:"sin(θ) = opposite/hypotenuse = 6/10 = 0.6.", tip:"SOHCAHTOA: Sin = Opposite / Hypotenuse." }
  ],
  probability: [
    { id:"p1", question:"A bag has 3 red and 5 blue balls. Probability of picking red?", options:["3/8","5/8","1/2","3/5"], answer:0, difficulty:"easy", xp:20, explanation:"P(red) = 3/(3+5) = 3/8.", tip:"Always add all outcomes to get the denominator." },
    { id:"p2", question:"What is the probability of getting a head in a fair coin toss?", options:["1/4","1","1/2","2/3"], answer:2, difficulty:"easy", xp:20, explanation:"P(head) = 1/2. A fair coin has 2 equally likely outcomes.", tip:"P(event) = favorable outcomes / total outcomes." },
    { id:"p3", question:"P(A ∪ B) = P(A) + P(B) when A and B are:", options:["Independent","Mutually exclusive","Complementary","Exhaustive"], answer:1, difficulty:"medium", xp:40, explanation:"When events cannot occur at the same time (mutually exclusive), P(A∪B) = P(A)+P(B).", tip:"Mutually exclusive = no overlap. Like rolling a 1 OR a 2 on a die." },
    { id:"p4", question:"A die is rolled. P(even number) = ?", options:["1/6","1/2","1/3","2/3"], answer:1, difficulty:"easy", xp:20, explanation:"Even numbers on a die: 2,4,6 — that's 3 out of 6. P = 3/6 = 1/2.", tip:"Count the favorable outcomes first, then divide by total." },
    { id:"p5", question:"If P(A) = 0.4, what is P(A') (complement)?", options:["0.4","0.6","1.4","0.04"], answer:1, difficulty:"easy", xp:20, explanation:"P(A') = 1 - P(A) = 1 - 0.4 = 0.6.", tip:"P(event) + P(complement) = 1. Always." },
    { id:"p6", question:"Two dice are rolled. P(sum = 7)?", options:["1/6","5/36","6/36","7/36"], answer:2, difficulty:"medium", xp:40, explanation:"Pairs that sum to 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 pairs out of 36. P = 6/36 = 1/6.", tip:"Total outcomes for 2 dice = 6×6 = 36. List systematic pairs." },
    { id:"p7", question:"A card is drawn from 52 cards. P(king) = ?", options:["1/13","4/52","Both A and B","1/4"], answer:2, difficulty:"easy", xp:20, explanation:"4 kings in 52 cards. P = 4/52 = 1/13. Both options are equal.", tip:"4/52 simplifies to 1/13. Always simplify fractions." },
    { id:"p8", question:"P(A and B) when A and B are independent = ?", options:["P(A)+P(B)","P(A)×P(B)","P(A)-P(B)","P(A)/P(B)"], answer:1, difficulty:"medium", xp:40, explanation:"For independent events: P(A∩B) = P(A) × P(B).", tip:"Independent means one event doesn't affect the other." },
    { id:"p9", question:"What is the sample space for flipping 2 coins?", options:["{H,T}","{HH,TT}","{HH,HT,TH,TT}","{H,H,T,T}"], answer:2, difficulty:"easy", xp:20, explanation:"Each coin has 2 outcomes. Total = 2×2 = 4 equally likely outcomes.", tip:"List all possibilities systematically: HH, HT, TH, TT." },
    { id:"p10", question:"If P(A)=0.3 and P(B)=0.5, P(A∪B) when mutually exclusive?", options:["0.15","0.8","0.2","1.0"], answer:1, difficulty:"medium", xp:40, explanation:"P(A∪B) = P(A)+P(B) = 0.3+0.5 = 0.8 (mutually exclusive).", tip:"Add probabilities only when events are mutually exclusive." }
  ],
  statistics: [
    { id:"s1", question:"What is the mean of: 2, 4, 6, 8, 10?", options:["5","6","7","8"], answer:1, difficulty:"easy", xp:20, explanation:"Mean = sum/count = (2+4+6+8+10)/5 = 30/5 = 6.", tip:"Mean = Sum of all values ÷ Number of values." },
    { id:"s2", question:"What is the median of: 3, 1, 4, 1, 5?", options:["1","3","4","2.8"], answer:1, difficulty:"easy", xp:20, explanation:"Sorted: 1,1,3,4,5. Middle value (3rd of 5) = 3.", tip:"Always sort data first before finding the median." },
    { id:"s3", question:"What is the mode of: 2, 3, 3, 4, 5, 3?", options:["2","4","3","5"], answer:2, difficulty:"easy", xp:20, explanation:"3 appears 3 times — more than any other value.", tip:"Mode = most frequently occurring value." },
    { id:"s4", question:"Standard deviation measures:", options:["Average value","Spread of data","Total sum","Middle value"], answer:1, difficulty:"medium", xp:40, explanation:"Standard deviation measures how spread out data is from the mean.", tip:"High SD = data is spread out. Low SD = data is clustered near the mean." },
    { id:"s5", question:"Range of: 12, 7, 3, 14, 6 is:", options:["11","7","14","3"], answer:0, difficulty:"easy", xp:20, explanation:"Range = Max - Min = 14 - 3 = 11.", tip:"Range = Largest value - Smallest value." },
    { id:"s6", question:"If mean = 50 and each value increases by 5, new mean = ?", options:["50","55","45","250"], answer:1, difficulty:"medium", xp:40, explanation:"Adding a constant to all values shifts the mean by the same constant. New mean = 50+5 = 55.", tip:"Shifting all data by k shifts the mean by k too." },
    { id:"s7", question:"A dataset has mean 10, median 10, mode 10. Distribution is:", options:["Left-skewed","Right-skewed","Symmetric","Bimodal"], answer:2, difficulty:"medium", xp:40, explanation:"When mean = median = mode, the distribution is perfectly symmetric (bell curve).", tip:"Skewed distributions have mean ≠ median ≠ mode." },
    { id:"s8", question:"Which measure is most affected by extreme values (outliers)?", options:["Mode","Median","Mean","Range"], answer:2, difficulty:"medium", xp:40, explanation:"The mean uses all values in calculation, so one extreme value can pull it far.", tip:"Use median when data has outliers — it's more robust." }
  ],
  equations: [
    { id:"e1", question:"Solve: 2x + 5 = 13", options:["x=3","x=4","x=5","x=9"], answer:1, difficulty:"easy", xp:20, explanation:"2x = 13-5 = 8. x = 8/2 = 4.", tip:"Isolate x: subtract from both sides, then divide." },
    { id:"e2", question:"If x² = 25, what is x?", options:["5","-5","±5","√25"], answer:2, difficulty:"easy", xp:20, explanation:"x² = 25 means x = +5 or x = -5. Both are valid solutions.", tip:"Square root gives two solutions: positive and negative." },
    { id:"e3", question:"Solve: 3x - 7 = 2x + 4", options:["x=3","x=11","x=1","x=-11"], answer:1, difficulty:"medium", xp:40, explanation:"3x - 2x = 4 + 7 → x = 11.", tip:"Move x terms to one side, constants to the other." },
    { id:"e4", question:"What are the roots of x² - 5x + 6 = 0?", options:["2,3","1,6","-2,-3","5,6"], answer:0, difficulty:"medium", xp:40, explanation:"Factor: (x-2)(x-3)=0 → x=2 or x=3.", tip:"Find two numbers that multiply to 6 and add to -5: those are -2 and -3... wait, positive factors: 2×3=6, 2+3=5. Signs: both negative gives +6 and -5." },
    { id:"e5", question:"Solve: x/3 = 9", options:["x=3","x=27","x=12","x=6"], answer:1, difficulty:"easy", xp:20, explanation:"Multiply both sides by 3: x = 9×3 = 27.", tip:"Eliminate fractions by multiplying both sides by the denominator." },
    { id:"e6", question:"Which is a linear equation?", options:["x²+2=0","3x+7=0","x³=8","1/x=5"], answer:1, difficulty:"easy", xp:20, explanation:"3x+7=0 has highest power of 1 — that's linear. Others have powers > 1 or inverse.", tip:"Linear = highest power of variable is 1." },
    { id:"e7", question:"Solve the system: x+y=5, x-y=1", options:["x=3,y=2","x=4,y=1","x=2,y=3","x=1,y=4"], answer:0, difficulty:"medium", xp:40, explanation:"Add equations: 2x=6 → x=3. Substitute: 3+y=5 → y=2.", tip:"Add or subtract equations to eliminate one variable first." },
    { id:"e8", question:"If 4x = 20, then 2x = ?", options:["5","10","40","8"], answer:1, difficulty:"easy", xp:20, explanation:"x = 5, so 2x = 10. Or simply: 4x=20 → 2x=10 (divide both by 2).", tip:"You don't always need to fully solve — manipulate the equation directly." }
  ],
  sets: [
    { id:"st1", question:"If A={1,2,3} and B={2,3,4}, what is A∩B?", options:["{1,2,3,4}","{2,3}","{1,4}","{1,2,3}"], answer:1, difficulty:"easy", xp:20, explanation:"A∩B = elements in BOTH A and B = {2,3}.", tip:"∩ means intersection = common elements." },
    { id:"st2", question:"If A={1,2,3} and B={2,3,4}, what is A∪B?", options:["{2,3}","{1,4}","{1,2,3,4}","{1,2}"], answer:2, difficulty:"easy", xp:20, explanation:"A∪B = all elements in A or B = {1,2,3,4}.", tip:"∪ means union = combine all, no duplicates." },
    { id:"st3", question:"What is the complement of A if U={1,2,3,4,5} and A={1,3}?", options:["{2,4,5}","{1,3}","{3,4,5}","{1,2}"], answer:0, difficulty:"easy", xp:20, explanation:"A' = U - A = {1,2,3,4,5} - {1,3} = {2,4,5}.", tip:"Complement = everything in the universal set NOT in A." },
    { id:"st4", question:"How many subsets does {a, b, c} have?", options:["3","6","8","9"], answer:2, difficulty:"medium", xp:40, explanation:"Number of subsets = 2ⁿ where n = number of elements = 2³ = 8.", tip:"Formula: 2ⁿ includes empty set and the set itself." },
    { id:"st5", question:"A-B (set difference) means:", options:["A∩B","Elements in A not in B","Elements in B not in A","A∪B"], answer:1, difficulty:"medium", xp:40, explanation:"A-B = elements that are in A but NOT in B.", tip:"Think of A-B as 'A minus the parts shared with B'." },
    { id:"st6", question:"If n(A)=10, n(B)=8, n(A∩B)=3, then n(A∪B)=?", options:["15","21","18","11"], answer:0, difficulty:"medium", xp:40, explanation:"n(A∪B) = n(A)+n(B)-n(A∩B) = 10+8-3 = 15.", tip:"Use inclusion-exclusion: add both, subtract the overlap." },
    { id:"st7", question:"What is a null/empty set?", options:["A set with one element","A set with no elements","A set equal to {0}","Universal set"], answer:1, difficulty:"easy", xp:20, explanation:"Empty set (∅) contains no elements — it's {} or ∅.", tip:"∅ ≠ {0}. {0} has one element (zero). ∅ has zero elements." }
  ],
  triangles: [
    { id:"tr1", question:"Sum of all angles in a triangle is:", options:["90°","180°","270°","360°"], answer:1, difficulty:"easy", xp:20, explanation:"The angle sum property: all three angles in any triangle add up to 180°.", tip:"This is the most fundamental triangle property — always 180°." },
    { id:"tr2", question:"In a right triangle, if one leg=3, other leg=4, hypotenuse=?", options:["5","7","6","√7"], answer:0, difficulty:"easy", xp:20, explanation:"Pythagoras: a²+b²=c² → 9+16=25 → c=5. The classic 3-4-5 triangle!", tip:"3-4-5 is the most common Pythagorean triple. Memorize it!" },
    { id:"tr3", question:"An equilateral triangle has all angles equal to:", options:["90°","45°","60°","30°"], answer:2, difficulty:"easy", xp:20, explanation:"All 3 sides equal → all 3 angles equal → 180°/3 = 60° each.", tip:"Equilateral = equal sides = equal angles = 60° each." },
    { id:"tr4", question:"Area of a triangle = ?", options:["base × height","(1/2) × base × height","base²","2 × base × height"], answer:1, difficulty:"easy", xp:20, explanation:"Area = ½ × base × height. The triangle is half a rectangle.", tip:"Think of it as half a rectangle with the same base and height." },
    { id:"tr5", question:"In triangle ABC, if ∠A=60° and ∠B=70°, then ∠C=?", options:["50°","60°","70°","130°"], answer:0, difficulty:"easy", xp:20, explanation:"∠C = 180° - 60° - 70° = 50°.", tip:"Use the angle sum property: ∠A + ∠B + ∠C = 180°." },
    { id:"tr6", question:"Which of these can be side lengths of a triangle?", options:["1,2,3","5,5,10","3,4,5","1,1,10"], answer:2, difficulty:"medium", xp:40, explanation:"Triangle inequality: sum of any 2 sides > 3rd side. 3+4=7>5 ✓", tip:"Check: the sum of the two shorter sides must be GREATER than the longest." },
    { id:"tr7", question:"In a 45-45-90 triangle, if legs = 1, hypotenuse = ?", options:["√2","2","√3","1"], answer:0, difficulty:"medium", xp:40, explanation:"Using Pythagoras: 1²+1² = c² → c = √2.", tip:"45-45-90 triangle ratios: 1 : 1 : √2." },
    { id:"tr8", question:"Two triangles are similar if they have:", options:["Equal areas","Equal angles","Equal perimeters","Equal sides"], answer:1, difficulty:"medium", xp:40, explanation:"Similar triangles have the same angles (AA similarity). Sides are proportional but not necessarily equal.", tip:"Similar = same shape, possibly different size. Congruent = same shape AND size." }
  ]
};

// Shuffle and get N random questions for a topic
function getQuestions(topic, count = 10) {
  const pool = QUESTIONS[topic] || [];
  const shuffled = [...pool].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, pool.length));
}
